### ISSUE TITLE
singleInstrumentationCall error

### ISSUE THREAD

**Issue by hram** [jaredsburrows/gradle-spoon-plugin#13]
I'v test project with this spoon config

> spoon {
>     if (project.hasProperty('spoonPackageName')) {
>         instrumentationArgs = ['package:' + project.spoonPackageName]
>     }
> }

and I run tests by this command
> gradlew clean spoonDebugAndroidTest -PspoonPackageName=hram.testspoon.package1

In 'hram.testspoon.package1' I'v 2 classes with 1 test in each
The problem is that after 2 tests succes run in junit report I'v only one last test

After issues search I'm added parametr singleInstrumentationCall and spoon config like this

> spoon {
>     if (project.hasProperty('spoonPackageName')) {
>         instrumentationArgs = ['package:' + project.spoonPackageName]
>     }
>     singleInstrumentationCall=true
> }

But in this case 'package' parameter is ignored and runs all tests in project
And good news is that junit report have all tests )

How can I fix that?

**Comment by jaredsburrows** [comment]
@hram This is currently supported: https://github.com/jaredsburrows/gradle-spoon-plugin/blob/7030f27634da5c8666c53a918de0278a45e2f8f8/src/test/groovy/com/jaredsburrows/spoon/SpoonPluginSpec.groovy#L67.

**Comment by hram** [comment]
@jaredsburrows pardon for my english
But can you read my message?
I know about singleInstrumentationCall 
And I wrote about it
The broblem is: "When I set up singleInstrumentationCall  = true then package parameter is ignored and runs all available tests instead of specific package"

**Comment by jaredsburrows** [comment]
I see. I believe this is another limitation by Spoon 2. 

Have you tried using the `@SmallTest`, `@MediumTest` and `@LargeTest` annotations?

**Comment by jaredsburrows** [comment]
Any update on this?

**Comment by hram** [comment]
In my test project https://github.com/hram/TestSpoonWeblate I have 3 tests:
- two small tests 
- single large test

if I setup spoon like this

> testSize = "SMALL"
>  singleInstrumentationCall = true

as a result spoon runs all 3 tests

**Comment by moodytux** [comment]
I'm also seeing this issue, where setting the parameter "singleInstrumentationCall = true" doesn't shard the tests across devices and instead runs all tests on all devices.

Looking into the logging from running this, it appears that the correct command runs to start with:

11:03:30 I/RemoteAndroidTest: Running am instrument -w -r   -e shardIndex 1 -e numShards 2 -e log true uk.co.fakedomain.myapp.test/uk.co.fakedomain.myapp.espresso.TestAndroidJUnitRunner on Nexus_4_API_23_Swiftshader_1_64bit [emulator-5554]
11:03:30 I/RemoteAndroidTest: Running am instrument -w -r   -e shardIndex 0 -e numShards 2 -e log true uk.co.fakedomain.myapp.test/uk.co.fakedomain.myapp.espresso.TestAndroidJUnitRunner on Nexus_4_API_23_Swiftshader_2_64bit [emulator-5556]

however, shortly after it runs another command gets run which is breaking the sharding:

2018-01-30 11:03:31 [SDR.run] Ignored tests: []
2018-01-30 11:03:31 [SDR.run] Ignored tests: []
2018-01-30 11:03:31 [SDR.run] Running all tests in a single instrumentation call [emulator-5556]
2018-01-30 11:03:31 [SDR.run] Running all tests in a single instrumentation call [emulator-5554]
2018-01-30 11:03:31 [SDR.runTestOnDevice] Running tests [emulator-5554]
2018-01-30 11:03:31 [SDR.runTestOnDevice] Running tests [emulator-5556]
11:03:31 I/RemoteAndroidTest: Running am instrument -w -r   uk.co.fakedomain.myapp.test/uk.co.fakedomain.myapp.espresso.TestAndroidJUnitRunner on Nexus_4_API_23_Swiftshader_1_64bit [emulator-5554]
11:03:31 I/RemoteAndroidTest: Running am instrument -w -r   uk.co.fakedomain.myapp.test/uk.co.fakedomain.myapp.espresso.TestAndroidJUnitRunner on Nexus_4_API_23_Swiftshader_2_64bit [emulator-5556]

as there are no shard options specified. Presumably this section was added for when running multiple instrumention calls, because in such case the commands in the second block include the '-e class' parameter so this issue doesn't present itself.

**Comment by moodytux** [comment]
I've just noticed that perhaps this is an issue with the underlying spoon library: https://github.com/square/spoon/issues/509

**Comment by jaredsburrows** [comment]
@hram I will fix the "testsize".

**Comment by jaredsburrows** [comment]
@moodytux I hope that fixes the issue soon!

**Comment by jaredsburrows** [comment]
`singleInstrumentationCall ` is supported.
`testSize` is being fixed here: https://github.com/jaredsburrows/gradle-spoon-plugin/pull/24.
